name: "Static Analysis"

on:
  push:
    branches:
      - '**'
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/static-analysis.yml'

  pull_request:

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.3, 8.4 ]
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Execute static analysis
        run: ./vendor/bin/phpstan --error-format=github
